// 这里的标题决定了你主页卡片上显示的名称
const lessonIndex = {
    1: "A Private Conversation",
    2: "Breakfast or Lunch?",
    3: "Please Send Me a Card",
    4: "An Exciting Trip",
    5: "No Wrong Numbers",
    6: "Percy Buttons",
    7: "Too Late",
    8: "The Best and the Worst",
    9: "A Cold Welcome",
    10: "Not for Jazz",
   11: "One Good Turn Deserves Another",
  12: "Goodbye and Good Luck",
  13: "The Greenwood Boys",
  14: "Do You Speak English?",
  15: "Good News",
  16: "A Polite Request",
  17: "Always Young",
  18: "He Often Does This!",
  19: "Sold Out",
  20: "One Man in a Boat",
  21: "Mad or Not?",
  22: "A Glass Envelope",
  23: "A New House",
  24: "It Could Be Worse",
  25: "Do the English Speak English?",
  26: "The Best Art Critics",
  27: "A Wet Night",
  28: "No Parking",
  29: "Taxi!",
  30: "Football or Polo?",
  31: "Success Story",
  32: "Shopping Made Easy",
  33: "Out of the Darkness",
  34: "Quick Work",
  35: "Stop Thief!",
  36: "Across the Channel",
  37: "The Olympic Games",
  38: "Everything Except the Weather",
  39: "Am I All Right?",
  40: "Food and Talk",
  41: "Do You Call That a Hat?",
  42: "Not Very Musical",
  43: "Over the South Pole",
  44: "Through the Forest",
  45: "A Clear Conscience",
  46: "Expensive and Uncomfortable",
  47: "A Thirsty Ghost",
  48: "Did You Want to Tell Me Something?",
  49: "The End of a Dream",
  50: "Taken for a Ride",
  51: "Reward for Virtue",
  52: "A Pretty Carpet",
  53: "Hot Snake",
  54: "Sticky Fingers",
  55: "Not a Gold Mine",
  56: "Faster Than Sound!",
  57: "Can I Help You, Madam?",
  58: "A Blessing in Disguise?",
  59: "In or Out?",
  60: "The Future",
  61: "Trouble with the Hubble",
  62: "After the Fire",
  63: "She Was Not Amused",
  64: "The Channel Tunnel",
  65: "Jumbo versus the Police",
  66: "Sweet as Honey!",
  67: "Volcanoes",
  68: "Persistent",
  69: "But Not Murder!",
  70: "Red for Danger",
  71: "A Famous Clock",
  72: "A Car Called Bluebird",
  73: "The Record-holder",
  74: "Out of the Limelight",
  75: "SOS",
  76: "April Fools' Day",
  77: "A Successful Operation",
  78: "The Last One?",
  79: "By Air",
  80: "The Crystal Palace",
  81: "Escape",
  82: "Monster or Fish?",
  83: "After the Elections",
  84: "On Strike",
  85: "Never Too Old to Learn",
  86: "Out of Control",
  87: "A Perfect Alibi",
  88: "Trapped in a Mine",
  89: "A Slip of the Tongue",
  90: "What's for Supper?",
  91: "Three Men in a Basket",
  92: "Asking for Trouble",
  93: "A Noble Gift",
  94: "Future Champions",
  95: "A Fantasy",
  96: "The Dead Return",
    // ... 依此类推，写到你目前拥有的课程编号
};
